name: rv_sistema_mobile
description: Mobile app for Sistema Empresa
publish_to: "none"
version: 1.0.9+11

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3
  google_fonts: ^6.1.0
  http: ^1.2.1
  image: ^4.5.4
  image_picker: ^1.0.7
  intl: ^0.19.0
  open_filex: ^4.5.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  printing: ^5.12.0
  share_plus: ^10.0.2
  signature: ^5.4.0
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/logo.png
